# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ipinfo_pb2 as ipinfo__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ipinfo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IPInfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayIpInfo = channel.unary_unary(
                '/ipinfo.IPInfoService/SayIpInfo',
                request_serializer=ipinfo__pb2.IpRequest.SerializeToString,
                response_deserializer=ipinfo__pb2.IpReply.FromString,
                _registered_method=True)


class IPInfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayIpInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IPInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayIpInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SayIpInfo,
                    request_deserializer=ipinfo__pb2.IpRequest.FromString,
                    response_serializer=ipinfo__pb2.IpReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ipinfo.IPInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ipinfo.IPInfoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IPInfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayIpInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipinfo.IPInfoService/SayIpInfo',
            ipinfo__pb2.IpRequest.SerializeToString,
            ipinfo__pb2.IpReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
