# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ipinfo.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ipinfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cipinfo.proto\x12\x06ipinfo\"\x17\n\tIpRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"\x85\x01\n\x07IpReply\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0e\n\x06region\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\x12\x10\n\x08location\x18\x05 \x01(\t\x12\x0b\n\x03org\x18\x06 \x01(\t\x12\x0e\n\x06postal\x18\x07 \x01(\t\x12\x10\n\x08timezone\x18\x08 \x01(\t2@\n\rIPInfoService\x12/\n\tSayIpInfo\x12\x11.ipinfo.IpRequest\x1a\x0f.ipinfo.IpReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipinfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IPREQUEST']._serialized_start=24
  _globals['_IPREQUEST']._serialized_end=47
  _globals['_IPREPLY']._serialized_start=50
  _globals['_IPREPLY']._serialized_end=183
  _globals['_IPINFOSERVICE']._serialized_start=185
  _globals['_IPINFOSERVICE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
